<?php
/**
 * index.phtml - POS Checkout Page
 **
 * @category Template
 * @package POS
 * @author Verein onePlace
 * @copyright (C) 2021  Verein onePlace <admin@1plc.ch>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0.0
 * @since 1.0.0
 */

$this->InlineScript()
    ->appendFile($this->basePath() . '/pos/js/checkout.js');
?>
<h1>Kasse</h1>

<div class="row text-center">
    <div class="col-md-4">

    </div>
    <div class="col-md-4 card">
        <h1 class="checkout-total">0.00</h1>
    </div>
</div>
<div class="row py-2">
    <div class="col-md-12 text-center">
        <a href="/pos/checkout/done/1" class="btn btn-primary">Buchen + Drucken</a>
        <a href="/pos/checkout/done/0" class="btn btn-secondary">Buchen</a>
        <a href="/pos/checkout" class="btn btn-secondary">Reset</a>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <ul class="list-group pos-checkout-list"></ul>
    </div>
    <div class="col-md-10">
        <div class="row">
            <?php
            foreach($aArticles as $oArt) {
                $sIcon = 'icon_burger.jpg';

                if($oArt->category[0]->id == '19') {
                    $sIcon = 'icon_pommes.jpg';
                }
                if($oArt->category[0]->id == '20') {
                    $sIcon = 'icon_waffel.png';
                }
                if($oArt->category[0]->id == '21') {
                    $sIcon = 'icon_menu.png';
                }
                ?>
                <div class="col-md-1">
                    <div class="card p-1 pos-checkout-add" plc-article-id="<?=$oArt->id?>" plc-article-label="<?=$oArt->label?>" plc-article-price="<?=$oArt->price_sell?>">
                        <img src="/pos/img/<?=$sIcon?>" style="max-width:100%;" />
                        <?=$oArt->label?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>